# Form implementation generated from reading ui file 'add_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import json
import os
from PyQt6.QtWidgets import QFileDialog


class Ui_addDialog(object):
    def setupUi(self, addDialog):
        addDialog.setObjectName("addDialog")
        addDialog.resize(440, 328)
        self.centralwidget = QtWidgets.QWidget(parent=addDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 441, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleFrame = QtWidgets.QFrame(parent=self.frame)
        self.titleFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleFrame)
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.titleFrame)
        self.titleLabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout.addWidget(self.titleLabel)
        self.txtname = QtWidgets.QLineEdit(parent=self.titleFrame)
        self.txtname.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtname.setObjectName("txtname")
        self.horizontalLayout.addWidget(self.txtname)
        self.verticalLayout_2.addWidget(self.titleFrame)
        self.releasedateFrame = QtWidgets.QFrame(parent=self.frame)
        self.releasedateFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.releasedateFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.releasedateFrame.setObjectName("releasedateFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.releasedateFrame)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.releasedateLabel = QtWidgets.QLabel(parent=self.releasedateFrame)
        self.releasedateLabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.releasedateLabel.setFont(font)
        self.releasedateLabel.setObjectName("releasedateLabel")
        self.horizontalLayout_2.addWidget(self.releasedateLabel)
        self.txtBirthday = QtWidgets.QDateEdit(parent=self.releasedateFrame)
        self.txtBirthday.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtBirthday.setObjectName("txtBirthday")
        self.horizontalLayout_2.addWidget(self.txtBirthday)
        self.verticalLayout_2.addWidget(self.releasedateFrame)
        self.imageFrame = QtWidgets.QFrame(parent=self.frame)
        self.imageFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.imageFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.imageFrame.setObjectName("imageFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.imageFrame)
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.imageLabel = QtWidgets.QLabel(parent=self.imageFrame)
        self.imageLabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.imageLabel.setFont(font)
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout_3.addWidget(self.imageLabel)
        self.uploadImgButton = QtWidgets.QToolButton(parent=self.imageFrame)
        self.uploadImgButton.setMinimumSize(QtCore.QSize(100, 0))
        self.uploadImgButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.uploadImgButton.setFont(font)
        self.uploadImgButton.setCheckable(True)
        self.uploadImgButton.setAutoExclusive(True)
        self.uploadImgButton.setObjectName("uploadImgButton")
        self.horizontalLayout_3.addWidget(self.uploadImgButton)
        self.verticalLayout_2.addWidget(self.imageFrame)
        self.ratingFrame = QtWidgets.QFrame(parent=self.frame)
        self.ratingFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ratingFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ratingFrame.setObjectName("ratingFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ratingFrame)
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ratingLabel = QtWidgets.QLabel(parent=self.ratingFrame)
        self.ratingLabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ratingLabel.setFont(font)
        self.ratingLabel.setObjectName("ratingLabel")
        self.horizontalLayout_4.addWidget(self.ratingLabel)
        self.comboBox = QtWidgets.QComboBox(parent=self.ratingFrame)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertBeforeCurrent)
        self.comboBox.setMinimumContentsLength(1)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_2.addWidget(self.ratingFrame)
        self.urlFrame = QtWidgets.QFrame(parent=self.frame)
        self.urlFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.urlFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.urlFrame.setObjectName("urlFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.urlFrame)
        self.horizontalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.urlLabel = QtWidgets.QLabel(parent=self.urlFrame)
        self.urlLabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.urlLabel.setFont(font)
        self.urlLabel.setObjectName("urlLabel")
        self.horizontalLayout_5.addWidget(self.urlLabel)
        self.rdoMale = QtWidgets.QRadioButton(parent=self.urlFrame)
        self.rdoMale.setObjectName("rdoMale")
        self.horizontalLayout_5.addWidget(self.rdoMale)
        self.rdoFemale = QtWidgets.QRadioButton(parent=self.urlFrame)
        self.rdoFemale.setObjectName("rdoFemale")
        self.horizontalLayout_5.addWidget(self.rdoFemale)
        self.verticalLayout_2.addWidget(self.urlFrame)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(-7, 270, 441, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        addDialog.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=addDialog)
        self.statusbar.setObjectName("statusbar")
        addDialog.setStatusBar(self.statusbar)

        self.retranslateUi(addDialog)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(addDialog)
        #sự kiện click button ok
        self.buttonBox.accepted.connect(self.save_to_json)
        #sự kiện click button cancel
        self.buttonBox.rejected.connect(addDialog.close)
        
        #sự kiện click button browse
        self.uploadImgButton.clicked.connect(self.upload_image)
    def retranslateUi(self, addDialog):
        _translate = QtCore.QCoreApplication.translate
        addDialog.setWindowTitle(_translate("addDialog", "MainWindow"))
        self.titleLabel.setText(_translate("addDialog", "Name"))
        self.releasedateLabel.setText(_translate("addDialog", "Birthday"))
        self.imageLabel.setText(_translate("addDialog", "Image"))
        self.uploadImgButton.setText(_translate("addDialog", "Browse"))
        self.ratingLabel.setText(_translate("addDialog", "Type of your pet"))
        self.comboBox.setItemText(0, _translate("addDialog", "Dog"))
        self.comboBox.setItemText(1, _translate("addDialog", "Cat"))
        self.comboBox.setItemText(2, _translate("addDialog", "Bird"))
        self.comboBox.setItemText(3, _translate("addDialog", "Fish"))
        self.comboBox.setItemText(4, _translate("addDialog", "Other"))
        self.urlLabel.setText(_translate("addDialog", "Sex"))
        self.rdoMale.setText(_translate("addDialog", "Male"))
        self.rdoFemale.setText(_translate("addDialog", "Female"))
    
    def upload_image(self):
        """Mở hộp thoại chọn ảnh và lưu đường dẫn."""
        file_dialog = QFileDialog()
        file_path, _ = file_dialog.getOpenFileName(filter="Images (*.png *.jpg *.jpeg *.bmp)")
        if file_path:
            self.image_path = file_path  # Lưu đường dẫn ảnh vào thuộc tính
        else:
            self.image_path = ""

    def save_to_json(self):
        """Lưu dữ liệu từ form vào tệp JSON."""
        # Lấy dữ liệu từ các trường
        name = self.txtname.text()
        birthday = self.txtBirthday.text()
        image = getattr(self, "image_path", "")  # Đường dẫn ảnh, mặc định là rỗng
        pet_type = self.comboBox.currentText()
        if self.rdoMale.isChecked():
            sex = "Male"
        elif self.rdoFemale.isChecked():
            sex = "Female"
        else:
            sex = None

        # Kiểm tra thông tin nhập vào
        if not name or not birthday or not pet_type or not sex:
            QtWidgets.QMessageBox.warning(None, "Error", "Please fill in all fields!")
            return

        # Tạo dictionary dữ liệu
        data = {
            "name": name,
            "birthday": birthday,
            "image": image,
            "type": pet_type,
            "sex": sex
        }

        # Ghi dữ liệu vào file data.json trong thư mục data
        file_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'data.json')
        with open(file_path, "r") as f:
            data_json = json.load(f)
            data_json["pets"].append(data)
        with open(file_path, "w") as f:
            json.dump(data_json, f)
        
        QtWidgets.QMessageBox.information(None, "Success", "Data added to JSON successfully!")

        # Reset form sau khi lưu
        self.reset_form()

    def reset_form(self):
        """Đặt lại form sau khi thêm thành công."""
        self.txtname.clear()
        self.txtBirthday.setDate(QtCore.QDate.currentDate())
        self.image_path = ""
        self.comboBox.setCurrentIndex(0)
        self.rdoMale.setChecked(False)
        self.rdoFemale.setChecked(False)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addDialog = QtWidgets.QMainWindow()
    ui = Ui_addDialog()
    ui.setupUi(addDialog)
    addDialog.show()
    sys.exit(app.exec())
