# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
from main_window import Ui_MainWindow
from register import Ui_R      
import json
import re

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(336, 440)
        Login.setStyleSheet("QPushButton#btnLogin{\n"
"    background-color: rgba(127, 108, 213, 0.8);\n"
"    color: rgba(197, 188, 234, 0.8);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#btnLogin:pressed{\n"
"    padding-left: 5px;;\n"
"    padding-top: 5px;\n"
"    padding-right: 5px;\n"
"    padding-bottom: 5px;\n"
"}\n"
"QPushButton#btnLogin:hover{\n"
"    background-color: rgba(241, 240, 247, 0.15);\n"
"}\n"
"QPushButton#btnRegister{\n"
"    background-color: rgba(127, 108, 213, 0.8);\n"
"    color: rgba(197, 188, 234, 0.8);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#btnRegister:pressed{\n"
"    padding-left: 5px;;\n"
"    padding-top: 5px;\n"
"    padding-right: 5px;\n"
"    padding-bottom: 5px;\n"
"}\n"
"QPushButton#btnRegister:hover{\n"
"    background-color: rgba(241, 240, 247, 0.15);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 281, 381))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.login = QtWidgets.QLabel(parent=self.widget)
        self.login.setGeometry(QtCore.QRect(0, 0, 281, 391))
        self.login.setStyleSheet("background-color: rgba(38, 4, 54, 0.76);\n"
"border-radius: 15px;\n"
"color:white;")
        self.login.setText("")
        self.login.setObjectName("login")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 261, 141))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../lesson8/lesson8/img/3766277.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.txtUsername = QtWidgets.QLineEdit(parent=self.widget)
        self.txtUsername.setGeometry(QtCore.QRect(100, 210, 171, 31))
        self.txtUsername.setStyleSheet("backgroud-color: white;\n"
"")
        self.txtUsername.setObjectName("txtUsername")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(10, 210, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 260, 71, 31))
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.widget)
        self.txtPassword.setGeometry(QtCore.QRect(100, 260, 171, 31))
        self.txtPassword.setObjectName("txtPassword")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(20, 310, 91, 21))
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.btnLogin = QtWidgets.QPushButton(parent=self.widget)
        self.btnLogin.setGeometry(QtCore.QRect(10, 340, 261, 31))
        self.btnLogin.setObjectName("btnLogin")
        self.btnLogin.clicked.connect(self.xu_ly_dang_nhap)      
        self.btnRegister = QtWidgets.QPushButton(parent=self.widget)
        self.btnRegister.setGeometry(QtCore.QRect(140, 310, 131, 21))
        self.btnRegister.setObjectName("btnRegister")
        self.btnRegister.clicked.connect(self.open_register_window)
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.label_3.setText(_translate("Login", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Đăng nhập vào hệ thống</span></p></body></html>"))
        self.label.setText(_translate("Login", "<html><head/><body><p align=\"center\">Tên đăng nhập</p></body></html>"))
        self.label_2.setText(_translate("Login", "<html><head/><body><p align=\"center\">Mật khẩu</p></body></html>"))
        self.label_5.setText(_translate("Login", "<html><head/><body><p align=\"center\">Quên mật khẩu ?</p></body></html>"))
        self.btnLogin.setText(_translate("Login", "Đăng nhập"))
        self.btnRegister.setText(_translate("Login", "Đăng kí"))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Đăng nhập vào hệ thống</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Tên đăng nhập</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Mật khẩu</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Quên mật khẩu ?</p></body></html>"))
        self.btnLogin.setText(_translate("MainWindow", "Đăng nhập"))
    #chuyen sang form dang ki
    def open_register_window(self):
        self.register_window = QtWidgets.QMainWindow()
        self.ui = Ui_R()
        self.ui.setupUi(self.register_window)
        self.register_window.show()    
    #thong bao loi
    def thong_bao_loi(self, set_title, set_text):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Icon.Information)
        msg.setText(set_text)
        msg.setWindowTitle(set_title)
        msg.exec()    
    
    def open_main_window(self):
        self.main_window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.main_window)
        self.main_window.show()
    def kiem_tra_dang_nhap(self, email, password):
        # Sử dụng đường dẫn tương đối
        file_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'account.json')
        with open(file_path, "r") as f:
            dataAccount = json.load(f)

        for i in dataAccount["accounts"]:
            if i["email"] == email and i["password"] == password:
                return True
        return False    
    def xu_ly_dang_nhap(self):    
        email = self.txtUsername.text()
        password = self.txtPassword.text()
        if self.kiem_tra_dang_nhap(email, password):
            self.open_main_window()
        else:
            self.thong_bao_loi("Lỗi", "Sai tên đăng nhập hoặc mật khẩu")
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
