# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from add_dialog import Ui_addDialog
from update_dialog import Ui_updateDialog
import os
import json
from PyQt6.QtWidgets import QTableWidget, QTableWidgetItem
from PyQt6.QtGui import QPixmap, QIcon
from PyQt6.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def openAddDialog(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_addDialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def openUpdateDialog(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_updateDialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 61, 591))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(10, 0, 47, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../lesson8/lesson8/img/15-giong-cho-canh-dep-de-cham-soc-pho-bien-tai-viet-nam-202201200909197585-fotor-20230801154436.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setGeometry(QtCore.QRect(0, 540, 31, 51))
        self.label_6.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_6.setPixmap(QtGui.QPixmap("../lesson8/lesson8/img/icons8-multiply-26.png"))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setGeometry(QtCore.QRect(30, 540, 31, 51))
        self.label_9.setText("")
        self.label_9.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_9.setPixmap(QtGui.QPixmap("../lesson8/lesson8/img/icons8-multiply-26.png"))
        self.label_9.setObjectName("label_9")
        #xu ly su kien click vao nut exit
        
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 100, 61, 51))
        self.pushButton_7.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../lesson8/lesson8/img/icons8-animal-shelter-50.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(300, 16))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 170, 61, 51))
        self.pushButton_8.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../lesson8/lesson8/img/icons8-animal-44.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(300, 16))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 240, 61, 51))
        self.pushButton_9.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../lesson8/lesson8/img/location.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setIconSize(QtCore.QSize(300, 16))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 310, 61, 51))
        self.pushButton_10.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../lesson8/lesson8/img/icons8-notification-64.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_10.setIcon(icon3)
        self.pushButton_10.setIconSize(QtCore.QSize(300, 16))
        self.pushButton_10.setObjectName("pushButton_10")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(70, 0, 731, 551))
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(0, 10, 721, 51))
        self.widget_3.setObjectName("widget_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_3)
        self.lineEdit.setGeometry(QtCore.QRect(70, 10, 351, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton.setGeometry(QtCore.QRect(450, 10, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 0, 71, 51))
        self.pushButton_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../lesson8/lesson8/img/TuongDii.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setIconSize(QtCore.QSize(200, 30))
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setAutoRepeat(False)
        self.pushButton_2.setAutoExclusive(False)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_2)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 80, 711, 511))
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.homePage.setAcceptDrops(False)
        self.homePage.setObjectName("homePage")
        self.frame = QtWidgets.QFrame(parent=self.homePage)
        self.frame.setGeometry(QtCore.QRect(0, 30, 721, 481))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 421, 481))
        self.label_7.setMinimumSize(QtCore.QSize(421, 481))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_7.setScaledContents(False)
        self.label_7.setWordWrap(False)
        self.label_7.setOpenExternalLinks(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.frame)
        self.label_8.setGeometry(QtCore.QRect(400, 10, 311, 471))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../lesson8/lesson8/img/3766277.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.homePage)
        self.crudPage = QtWidgets.QWidget()
        self.crudPage.setObjectName("crudPage")
        
        self.tableWidget = QTableWidget(parent=self.crudPage)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 711, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)  # Thiết lập số cột (Image, Name, Birthday, Type)
        self.tableWidget.setHorizontalHeaderLabels(["Image", "Name", "Birthday", "Type", "Sex"])
        self.tableWidget.horizontalHeader().setStretchLastSection(True)  # Cột cuối co giãn hết cỡ
        self.tableWidget.resizeColumnsToContents()  # Tự động chỉnh kích thước cột theo nội dung
        self.tableWidget.resizeRowsToContents()  # Tự động chỉnh kích thước hàng theo nội dung
        header = self.tableWidget.horizontalHeader()
        header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)

        self.pushButton_3 = QtWidgets.QPushButton(parent=self.crudPage)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 20, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.openAddDialog)  # Corrected connection
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.crudPage)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 20, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.crudPage)
        self.pushButton_5.setGeometry(QtCore.QRect(640, 20, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.openUpdateDialog)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.crudPage)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 20, 331, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.crudPage)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 20, 81, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget.addWidget(self.crudPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #ham hien thi thong tin len listWidget
        self.hien_thi_du_lieu("")

        # Kết nối các nút với hàm chuyển trang
        self.pushButton_7.clicked.connect(lambda: self.chuyen_trang(0))  # Trang đầu tiên
        self.pushButton_8.clicked.connect(lambda: self.chuyen_trang(1))  # Trang thứ hai
        self.pushButton_9.clicked.connect(lambda: self.chuyen_trang(2))  # Trang thứ ba
        # Đặt trang mặc định khi chạy chương trình
        self.stackedWidget.setCurrentIndex(0)  # Mặc định là trang đầu tiên

        #dong chuong trinh
        self.label_6.mousePressEvent = self.closeEvent
        #tim kiem
        self.pushButton.clicked.connect(self.search)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "EXIT"))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Welcome </span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Pet management software</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Add"))
        self.pushButton_4.setText(_translate("MainWindow", "Delete"))
        self.pushButton_5.setText(_translate("MainWindow", "Edit"))
        self.pushButton_6.setText(_translate("MainWindow", "Search"))
    #ham xu li tim kiem chi hien thi thong tin duoc tim kiem len tableWidget
    def search(self):
        search_term = self.lineEdit.text().lower()  # Lấy văn bản từ lineEdit và chuyển thành chữ thường để tìm kiếm không phân biệt chữ hoa chữ thường

    # Đọc dữ liệu từ file JSON
        file_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'data.json')
        with open(file_path, 'r') as file:
            data = json.load(file)

        pets = data.get("pets", [])

    # Lọc danh sách pets chỉ theo tên
        filtered_pets = [pet for pet in pets if search_term in pet["name"].lower()]

    # Hiển thị dữ liệu đã lọc
        self.hien_thi_du_lieu(filtered_pets)  # Cập nhật table với pets đã lọc

    #ham dong chuong trinh khi click vao nut exit hien thi thong bao
    def closeEvent(self, event):
        reply = QMessageBox.question(self, 'Message', 'Are you sure to quit?', QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No, QMessageBox.StandardButton.No)
        if reply == QMessageBox.StandardButton.Yes:
            event.accept()
        else:
            event.ignore()
    #ham hien thi thong tin len listWidget
    def hien_thi_du_lieu(self, data):
        # Đọc dữ liệu từ file data.json
        file_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'data.json')
        with open(file_path, 'r') as file:
            data = json.load(file)

        pets = data.get("pets", [])
        
        # Thiết lập số hàng và số cột
        self.tableWidget.setRowCount(len(data["pets"]))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setHorizontalHeaderLabels(["Image", "Name", "Birthday", "Type", "Sex"])

        # Thiết lập chiều rộng và chiều cao của cột và hàng
        self.tableWidget.setColumnWidth(0, 50)  # Cột hình ảnh rộng hơn
        self.tableWidget.verticalHeader().setDefaultSectionSize(100)  # Chiều cao hàng lớn hơn

        
        # Hiển thị dữ liệu lên tableWidget
        for i, pet in enumerate(pets):
            # Tải hình ảnh và phóng to sao cho chiếm toàn bộ không gian của ô
            pixmap = QPixmap(pet["image"])

            # Phóng to hình ảnh sao cho vừa với kích thước cột và hàng
            pixmap = pixmap.scaled(
                self.tableWidget.columnWidth(0),  # Đặt chiều rộng cột làm kích thước phóng to
                self.tableWidget.rowHeight(i),    # Đặt chiều cao hàng làm kích thước phóng to
                QtCore.Qt.AspectRatioMode.KeepAspectRatioByExpanding,  # Phóng to giữ tỷ lệ
                QtCore.Qt.TransformationMode.SmoothTransformation
            )
            # Tạo icon từ pixmap và thiết lập vào item của cột 0
            icon = QIcon(pixmap)
            item = QtWidgets.QTableWidgetItem()
            item.setIcon(icon)
            item.setFlags(QtCore.Qt.ItemFlag.ItemIsEnabled)  # Ngăn chỉnh sửa ô
            self.tableWidget.setItem(i, 0, item)
            self.tableWidget.setItem(i, 1, QTableWidgetItem(pet.get("name", "")))
            self.tableWidget.setItem(i, 2, QTableWidgetItem(pet.get("birthday", "")))
            self.tableWidget.setItem(i, 3, QTableWidgetItem(pet.get("type", "")))
            self.tableWidget.setItem(i, 4, QTableWidgetItem(pet.get("sex", "")))
    #ham chuyen trang khi cho vao nut pushButton_7, pushButton_8, pushButton_9
    def chuyen_trang(self, index):
        self.stackedWidget.setCurrentIndex(index)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
